language: csharp
solution: iRoad.sln
install:
  - nuget restore iRoad.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release solution-name.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.exe ./iRoad.Test/bin/Release/iRoad.Test.dll